
export const MARKET_LOADING = "MARKET_LOADING"
export const MARKET_LOADED = "MARKET_LOADED"
export const MARKET_LOADING_FAIL = "MARKET_LOADING_FAIL"
export const EXCHANGES_SET = "EXCHANGES_SET"
export const EXCHANGE_SET = "EXCHANGE_SET"
export const PAIR_SET = "PAIR_SET"
