
const enumAltcoin = {
  MARKET_LOADING: "MARKET_LOADING",
  MARKET_LOADED: "MARKET_LOADED",
  MARKET_LOADING_FAIL: "MARKET_LOADING_FAIL",
  EXCHANGES_SET: "EXCHANGES_SET",
  EXCHANGE_SET: "EXCHANGE_SET",
  PAIR_SET: "PAIR_SET"
}

export default Object.freeze(enumAltcoin)
